-- VHDL Entity DNP3_802_11_lib.Station80211.interface
--
-- Created:
--          by - Lucas.UNKNOWN (LUCAS-ACER64)
--          at - 16:44:05 19/07/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.STD_LOGIC_UNSIGNED.all;
USE IEEE.numeric_std.all;

ENTITY estacao180211 IS
   PORT( 
      clk_80211          : IN     std_logic;
      clk_10mhz          : in     std_logic;
      rst_80211          : IN     std_logic;      
      sen_tcpipllc1      : IN     std_logic_vector (2719 DOWNTO 0);
      sta_send_ack1      : IN     std_logic;
	  endtx1             : IN     std_logic;
	  endtx111            : in     std_logic;
	  channel_idle1      : IN     std_logic;
	  sta_rec_frame_len1 : IN  std_logic_vector (15 DOWNTO 0);
	  sta_rec_frame1     : IN    std_logic_vector (3007 DOWNTO 0);	
	  sta_send_frame1    : OUT    std_logic_vector (3007 DOWNTO 0);
      sta_send_frame_len1: OUT std_logic_vector (15 DOWNTO 0);
      rec_tcpipllc1      : OUT    std_logic_vector (2719 DOWNTO 0);
      sta_rec_ack1       : OUT    std_logic
      
   );


-- Declarations

END estacao180211 ;

--
-- VHDL Architecture DNP3_802_11_lib.Station80211.struct
--
-- Created:
--          by - Lucas.UNKNOWN (LUCAS-ACER64)
--          at - 16:44:06 19/07/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.STD_LOGIC_UNSIGNED.all;
USE IEEE.numeric_std.all;


--###################################################################
--LIBRARY DNP3_802_11_lib;   - Biblioteca criada com as entidades
--####################################################################
  

ARCHITECTURE struct OF estacao180211 IS

   -- Architecture declarations

   -- Internal signal declarations
   signal    nav1                :     std_logic;
   signal    sifs_flag1          :     std_logic;
   signal    difs_flag1          :     std_logic;
   signal    backoff_flag1       :     std_logic;
   signal    sifs_req1           :    std_logic;
   signal    difs_req1           :    std_logic;
   signal    backoff_req1        :    std_logic;
   signal    nav_req1            :    std_logic; 
   signal    duration1           :    integer; 
   


   -- Component Declarations
   COMPONENT SSM_MAC1
   PORT (
       clk_80211          : IN     std_logic;
       rst_80211          : IN     std_logic;
   --    myaddress          : in     std_logic_vector (47 downto 0);
   --    destaddress        : in     std_logic_vector (47 downto 0);
       
       -- time management interface
       nav1                : in     std_logic;
       sifs_flag1          : in     std_logic;
       difs_flag1          : in     std_logic;
       backoff_flag1       : in     std_logic;
       sifs_req1           : out    std_logic;
       difs_req1           : out    std_logic;
       backoff_req1        : out    std_logic;
       nav_req1            : out    std_logic;       ----- Adicionado
       
       -- tcp_ip_llc interface
       sen_tcpipllc1      : IN     std_logic_vector (2719 DOWNTO 0);
       rec_tcpipllc1      : OUT    std_logic_vector (2719 DOWNTO 0);
       sta_send_ack1       : IN     std_logic;
       sta_rec_ack1       : OUT    std_logic;
       
       -- phy layer interface
       endtx1               : in     std_logic;
       endtx111              : in     std_logic;
       channel_idle1        : in     std_logic;
       sta_rec_frame1      : IN     std_logic_vector (3007 DOWNTO 0);
       sta_rec_frame_len1  : IN     std_logic_vector (15 DOWNTO 0);
       sta_send_frame1     : OUT    std_logic_vector (3007 DOWNTO 0);
       sta_send_frame_len1 : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT time_management1
   PORT (
     -- general
       clk_80211          : IN     std_logic;
       clk_10mhz          : in     std_logic;
       rst_80211          : IN     std_logic;
       
       -- time management interface
       nav1                : out     std_logic;
       sifs_flag1          : out     std_logic;
       difs_flag1          : out     std_logic;
       backoff_flag1       : out     std_logic;
       sifs_req1           : in      std_logic;
       difs_req1           : in      std_logic;
       backoff_req1        : in      std_logic;
       nav_req1            : in      std_logic;
       duration1           : in      integer        --simulador de valor duração 
       
   );
   END COMPONENT;
   



--##############################################################################
   -- Optional embedded configurations
   -- pragma synthesis_off
--   FOR ALL : SAR_Backoff USE ENTITY DNP3_802_11_lib.SAR_Backoff;
--   FOR ALL : SAR_MAC USE ENTITY DNP3_802_11_lib.SAR_MAC;
--   FOR ALL : SAR_PHY USE ENTITY DNP3_802_11_lib.SAR_PHY;
--   FOR ALL : SSM_MAC USE ENTITY DNP3_802_11_lib.SSM_MAC;
--   FOR ALL : SSM_PHY USE ENTITY DNP3_802_11_lib.SSM_PHY;
--##############################################################################
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   AA_1 : SSM_MAC1
      PORT MAP (
         clk_80211 => clk_80211,
          rst_80211 => rst_80211,
         
          -- time management interface
          nav1          => nav1,
          sifs_flag1    => sifs_flag1, 
          difs_flag1    => difs_flag1, 
          backoff_flag1 => backoff_flag1, 
          sifs_req1     => sifs_req1, 
          difs_req1     => difs_req1, 
          backoff_req1  => backoff_req1, 
          nav_req1      => nav_req1,          
          
          -- tcp_ip_llc interface
          sen_tcpipllc1 => sen_tcpipllc1,
          rec_tcpipllc1 => rec_tcpipllc1, 
          sta_send_ack1  => sta_send_ack1, 
          sta_rec_ack1   => sta_rec_ack1,
          
      --    -- phy layer interface
          endtx1              => endtx1,
          endtx111             => endtx111,
          channel_idle1       => channel_idle1,
          sta_rec_frame1      => sta_rec_frame1, 
          sta_rec_frame_len1  => sta_rec_frame_len1, 
          sta_send_frame1     => sta_send_frame1, 
          sta_send_frame_len1 => sta_send_frame_len1 
      );
   AA_2 : time_management1
      PORT MAP (
          clk_80211 => clk_80211,
          clk_10Mhz => clk_10Mhz,
          rst_80211 => rst_80211,
          
          -- time management interface
          nav1          => nav1,
          sifs_flag1    => sifs_flag1, 
          difs_flag1    => difs_flag1, 
          backoff_flag1 => backoff_flag1, 
          sifs_req1     => sifs_req1, 
          difs_req1     => difs_req1, 
          nav_req1      => nav_req1, 
          duration1     => duration1,     -- Adicionado
          backoff_req1  => backoff_req1
          
      );
   

END struct;
