-- VHDL Entity DNP3_802_11_lib.Station80211.interface
--
-- Created:
--          by - Lucas.UNKNOWN (LUCAS-ACER64)
--          at - 16:44:05 19/07/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.STD_LOGIC_UNSIGNED.all;
USE IEEE.numeric_std.all;

ENTITY estacao_ocup_80211 IS
   PORT( 
      clk_80211          : IN     std_logic;
      clk_10mhz          : in     std_logic;
      rst_80211          : IN     std_logic;      
      sen_tcpipllc2      : IN     std_logic_vector (2719 DOWNTO 0);
      sta_send_ack2      : IN     std_logic;
	  endtx2             : IN     std_logic;
	  endtx222           : in     std_logic;
	  channel_idle2      : IN     std_logic;
	  sta_rec_frame_len2 : IN  std_logic_vector (15 DOWNTO 0);
	  sta_rec_frame2     : IN    std_logic_vector (3007 DOWNTO 0);	
	  sta_send_frame2    : OUT    std_logic_vector (3007 DOWNTO 0);
      sta_send_frame_len2: OUT std_logic_vector (15 DOWNTO 0);
      rec_tcpipllc2      : OUT    std_logic_vector (2719 DOWNTO 0);
      sta_rec_ack2       : OUT    std_logic
      
   );


-- Declarations

END estacao_ocup_80211 ;

--
-- VHDL Architecture DNP3_802_11_lib.Station80211.struct
--
-- Created:
--          by - Lucas.UNKNOWN (LUCAS-ACER64)
--          at - 16:44:06 19/07/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.STD_LOGIC_UNSIGNED.all;
USE IEEE.numeric_std.all;


--###################################################################
--LIBRARY DNP3_802_11_lib;   - Biblioteca criada com as entidades
--####################################################################

 
ARCHITECTURE struct OF estacao_ocup_80211 IS

   -- Architecture declarations

   -- Internal signal declarations
   signal    nav2                :     std_logic;
   signal    sifs_flag2          :     std_logic;
   signal    difs_flag2          :     std_logic;
   signal    backoff_flag2       :     std_logic;
   signal    sifs_req2           :    std_logic;
   signal    difs_req2           :    std_logic;
   signal    backoff_req2        :    std_logic;
   signal    nav_req2            :    std_logic; 
   signal    duration22           :    integer;
   


   -- Component Declarations
   COMPONENT SSM_MAC_ocup
   PORT (
       clk_80211          : IN     std_logic;
       rst_80211          : IN     std_logic;
   --    myaddress          : in     std_logic_vector (47 downto 0);
   --    destaddress        : in     std_logic_vector (47 downto 0);
       
       -- time management interface
       nav2                : in     std_logic;
       sifs_flag2          : in     std_logic;
       difs_flag2          : in     std_logic;
       backoff_flag2       : in     std_logic;
       sifs_req2           : out    std_logic;
       difs_req2           : out    std_logic;
       backoff_req2        : out    std_logic;
       nav_req2            : out    std_logic;       ----- Adicionado
       
       -- tcp_ip_llc interface
       sen_tcpipllc2      : IN     std_logic_vector (2719 DOWNTO 0);
       rec_tcpipllc2      : OUT    std_logic_vector (2719 DOWNTO 0);
       sta_send_ack2       : IN     std_logic;
       sta_rec_ack2       : OUT    std_logic;
        duration22           : out    integer;
       
       -- phy layer interface
       endtx2               : in     std_logic;
       endtx222              : in     std_logic;
       channel_idle2        : in     std_logic;
       sta_rec_frame2      : IN     std_logic_vector (3007 DOWNTO 0);
       sta_rec_frame_len2  : IN     std_logic_vector (15 DOWNTO 0);
       sta_send_frame2     : OUT    std_logic_vector (3007 DOWNTO 0);
       sta_send_frame_len2 : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT time_management_ocup
   PORT (
     -- general
       clk_80211          : IN     std_logic;
       clk_10mhz          : in     std_logic;
       rst_80211          : IN     std_logic;
       
       -- time management interface
       nav2                : out     std_logic;
       sifs_flag2          : out     std_logic;
       difs_flag2          : out     std_logic;
       backoff_flag2       : out     std_logic;
       sifs_req2           : in      std_logic;
       difs_req2           : in      std_logic;
       backoff_req2        : in      std_logic;
       nav_req2            : in      std_logic;
       duration22           : in      integer        --simulador de valor duração 
       
   );
   END COMPONENT;
   



--##############################################################################
   -- Optional embedded configurations
   -- pragma synthesis_off
--   FOR ALL : SAR_Backoff USE ENTITY DNP3_802_11_lib.SAR_Backoff;
--   FOR ALL : SAR_MAC USE ENTITY DNP3_802_11_lib.SAR_MAC;
--   FOR ALL : SAR_PHY USE ENTITY DNP3_802_11_lib.SAR_PHY;
--   FOR ALL : SSM_MAC USE ENTITY DNP3_802_11_lib.SSM_MAC;
--   FOR ALL : SSM_PHY USE ENTITY DNP3_802_11_lib.SSM_PHY;
--##############################################################################
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   AAA_1 : SSM_MAC_ocup
      PORT MAP (
         clk_80211 => clk_80211,
          rst_80211 => rst_80211,
         
          -- time management interface
          nav2          => nav2,
          sifs_flag2    => sifs_flag2, 
          difs_flag2    => difs_flag2, 
          backoff_flag2 => backoff_flag2, 
          sifs_req2     => sifs_req2, 
          difs_req2     => difs_req2, 
          backoff_req2  => backoff_req2, 
          nav_req2      => nav_req2,          
          
          -- tcp_ip_llc interface
          sen_tcpipllc2 => sen_tcpipllc2,
          rec_tcpipllc2 => rec_tcpipllc2, 
          sta_send_ack2  => sta_send_ack2, 
          sta_rec_ack2   => sta_rec_ack2,
          duration22     => duration22,
          
      --    -- phy layer interface
          endtx2              => endtx2,
          endtx222             => endtx222,
          channel_idle2       => channel_idle2,
          sta_rec_frame2      => sta_rec_frame2, 
          sta_rec_frame_len2  => sta_rec_frame_len2, 
          sta_send_frame2     => sta_send_frame2, 
          sta_send_frame_len2 => sta_send_frame_len2 
      );
   AAA_2 : time_management_ocup
      PORT MAP (
          clk_80211 => clk_80211,
          clk_10Mhz => clk_10Mhz,
          rst_80211 => rst_80211,
          
          -- time management interface
          nav2          => nav2,
          sifs_flag2    => sifs_flag2, 
          difs_flag2    => difs_flag2, 
          backoff_flag2 => backoff_flag2, 
          sifs_req2     => sifs_req2, 
          difs_req2     => difs_req2, 
          nav_req2      => nav_req2, 
          duration22     => duration22,     -- Adicionado
          backoff_req2  => backoff_req2
          
      );
   

END struct;
