-- VHDL Entity DNP3_802_11_lib.Station80211.interface
--
-- Created:
--          by - Lucas.UNKNOWN (LUCAS-ACER64)
--          at - 16:44:05 19/07/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.STD_LOGIC_UNSIGNED.all;
USE IEEE.numeric_std.all;

ENTITY estacao080211 IS
   PORT( 
      clk_80211          : IN     std_logic;
      clk_10mhz          : in     std_logic;
      rst_80211          : IN     std_logic;      
      sen_tcpipllc0      : IN     std_logic_vector (2719 DOWNTO 0);
      sta_send_ack0      : IN     std_logic;
	  endtx0             : IN     std_logic;
	  endtx000            : in     std_logic;
	  channel_idle0      : IN     std_logic;
	  sta_rec_frame_len0 : IN  std_logic_vector (15 DOWNTO 0);
	  sta_rec_frame0     : IN    std_logic_vector (3007 DOWNTO 0);	
	  sta_send_frame0    : OUT    std_logic_vector (3007 DOWNTO 0);
      sta_send_frame_len0: OUT std_logic_vector (15 DOWNTO 0);
      rec_tcpipllc0      : OUT    std_logic_vector (2719 DOWNTO 0);
      sta_rec_ack0       : OUT    std_logic
      
   );


-- Declarations

END estacao080211 ;

--
-- VHDL Architecture DNP3_802_11_lib.Station80211.struct
--
-- Created:
--          by - Lucas.UNKNOWN (LUCAS-ACER64)
--          at - 16:44:06 19/07/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.STD_LOGIC_UNSIGNED.all;
USE IEEE.numeric_std.all;


--###################################################################
--LIBRARY DNP3_802_11_lib;   - Biblioteca criada com as entidades
--####################################################################

 
ARCHITECTURE struct OF estacao080211 IS

   -- Architecture declarations

   -- Internal signal declarations
   signal    nav0                :     std_logic;
   signal    sifs_flag0          :     std_logic;
   signal    difs_flag0          :     std_logic;
   signal    backoff_flag0       :     std_logic;
   signal    sifs_req0           :    std_logic;
   signal    difs_req0           :    std_logic;
   signal    backoff_req0        :    std_logic;
   signal    nav_req0            :    std_logic; 
   signal    duration0           :    integer; 
   


   -- Component Declarations
   COMPONENT SSM_MAC0
   PORT (
       clk_80211          : IN     std_logic;
       rst_80211          : IN     std_logic;
   --    myaddress          : in     std_logic_vector (47 downto 0);
   --    destaddress        : in     std_logic_vector (47 downto 0);
       
       -- time management interface
       nav0                : in     std_logic;
       sifs_flag0          : in     std_logic;
       difs_flag0          : in     std_logic;
       backoff_flag0       : in     std_logic;
       sifs_req0           : out    std_logic;
       difs_req0           : out    std_logic;
       backoff_req0        : out    std_logic;
       nav_req0            : out    std_logic;       ----- Adicionado
       
       -- tcp_ip_llc interface
       sen_tcpipllc0      : IN     std_logic_vector (2719 DOWNTO 0);
       rec_tcpipllc0      : OUT    std_logic_vector (2719 DOWNTO 0);
       sta_send_ack0       : IN     std_logic;
       sta_rec_ack0       : OUT    std_logic;
       
       -- phy layer interface
       endtx0               : in     std_logic;
       endtx000              : in     std_logic;
       channel_idle0        : in     std_logic;
       sta_rec_frame0      : IN     std_logic_vector (3007 DOWNTO 0);
       sta_rec_frame_len0  : IN     std_logic_vector (15 DOWNTO 0);
       sta_send_frame0     : OUT    std_logic_vector (3007 DOWNTO 0);
       sta_send_frame_len0 : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT time_management0
   PORT (
     -- general
       clk_80211          : IN     std_logic;
       clk_10mhz          : in     std_logic;
       rst_80211          : IN     std_logic;
       
       -- time management interface
       nav0                : out     std_logic;
       sifs_flag0          : out     std_logic;
       difs_flag0          : out     std_logic;
       backoff_flag0       : out     std_logic;
       sifs_req0           : in      std_logic;
       difs_req0           : in      std_logic;
       backoff_req0        : in      std_logic;
       nav_req0            : in      std_logic;
       duration0           : in      integer        --simulador de valor duração 
       
   );
   END COMPONENT;
   



--##############################################################################
   -- Optional embedded configurations
   -- pragma synthesis_off
--   FOR ALL : SAR_Backoff USE ENTITY DNP3_802_11_lib.SAR_Backoff;
--   FOR ALL : SAR_MAC USE ENTITY DNP3_802_11_lib.SAR_MAC;
--   FOR ALL : SAR_PHY USE ENTITY DNP3_802_11_lib.SAR_PHY;
--   FOR ALL : SSM_MAC USE ENTITY DNP3_802_11_lib.SSM_MAC;
--   FOR ALL : SSM_PHY USE ENTITY DNP3_802_11_lib.SSM_PHY;
--##############################################################################
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   A_1 : SSM_MAC0
      PORT MAP (
         clk_80211 => clk_80211,
          rst_80211 => rst_80211,
         
          -- time management interface
          nav0          => nav0,
          sifs_flag0    => sifs_flag0, 
          difs_flag0    => difs_flag0, 
          backoff_flag0 => backoff_flag0, 
          sifs_req0     => sifs_req0, 
          difs_req0     => difs_req0, 
          backoff_req0  => backoff_req0, 
          nav_req0      => nav_req0,          
          
          -- tcp_ip_llc interface
          sen_tcpipllc0 => sen_tcpipllc0,
          rec_tcpipllc0 => rec_tcpipllc0, 
          sta_send_ack0  => sta_send_ack0, 
          sta_rec_ack0   => sta_rec_ack0,
          
      --    -- phy layer interface
          endtx0              => endtx0,
          endtx000             => endtx000,
          channel_idle0       => channel_idle0,
          sta_rec_frame0      => sta_rec_frame0, 
          sta_rec_frame_len0  => sta_rec_frame_len0, 
          sta_send_frame0     => sta_send_frame0, 
          sta_send_frame_len0 => sta_send_frame_len0 
      );
   A_2 : time_management0
      PORT MAP (
          clk_80211 => clk_80211,
          clk_10Mhz => clk_10Mhz,
          rst_80211 => rst_80211,
          
          -- time management interface
          nav0          => nav0,
          sifs_flag0    => sifs_flag0, 
          difs_flag0    => difs_flag0, 
          backoff_flag0 => backoff_flag0, 
          sifs_req0     => sifs_req0, 
          difs_req0     => difs_req0, 
          nav_req0      => nav_req0, 
          duration0     => duration0,     -- Adicionado
          backoff_req0  => backoff_req0
          
      );
   

END struct;
