-- VHDL Entity DNP3_802_11_lib.Station80211.interface
--
-- Created:
--          by - Lucas.UNKNOWN (LUCAS-ACER64)
--          at - 16:44:05 19/07/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.STD_LOGIC_UNSIGNED.all;
USE IEEE.numeric_std.all;

ENTITY fisico_mac0 IS
   PORT( 
      clk_80211          : IN     std_logic;
      clk_10mhz          : in     std_logic;
      rst_80211          : IN     std_logic;      
      sen_tcpipllc0      : IN     std_logic_vector (2719 DOWNTO 0);
      sta_send_ack0      : IN     std_logic;
      tx_fromsta10       : IN     std_logic_vector (3199 DOWNTO 0);
      endtx00             : IN     std_logic;
      endtx01            : OUT     std_logic;      
      sta_phy_tx0        : OUT    std_logic_vector (3199 DOWNTO 0);
      rec_tcpipllc0      : OUT    std_logic_vector (2719 DOWNTO 0);
      sta_rec_ack0       : OUT    std_logic
      
   );


-- Declarations

END fisico_mac0 ;

--
-- VHDL Architecture DNP3_802_11_lib.Station80211.struct
--
-- Created:
--          by - Lucas.UNKNOWN (LUCAS-ACER64)
--          at - 16:44:06 19/07/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.STD_LOGIC_UNSIGNED.all;
USE IEEE.numeric_std.all;


--###################################################################
--LIBRARY DNP3_802_11_lib;   - Biblioteca criada com as entidades
--####################################################################
 

ARCHITECTURE struct OF fisico_mac0 IS

   -- Architecture declarations

   -- Internal signal declarations

   
   signal      endtx0             :     std_logic;
   signal      endtx000            :     std_logic;
   signal      channel_idle0      :     std_logic;
   signal      sta_rec_frame_len0 :     std_logic_vector (15 DOWNTO 0);
   signal      sta_rec_frame0     :     std_logic_vector (3007 DOWNTO 0);    
   signal      sta_send_frame0    :     std_logic_vector (3007 DOWNTO 0);
   signal      sta_send_frame_len0:     std_logic_vector (15 DOWNTO 0);

   -- Component Declarations
   COMPONENT estacao080211
   PORT (
         clk_80211          : IN     std_logic;
         clk_10mhz          : in     std_logic;
         rst_80211          : IN     std_logic;      
         sen_tcpipllc0      : IN     std_logic_vector (2719 DOWNTO 0);
         sta_send_ack0      : IN     std_logic;
         endtx0             : IN     std_logic;
         endtx000            : in     std_logic;
         channel_idle0      : IN     std_logic;
         sta_rec_frame_len0 : IN  std_logic_vector (15 DOWNTO 0);
         sta_rec_frame0     : IN    std_logic_vector (3007 DOWNTO 0);    
         sta_send_frame0    : OUT    std_logic_vector (3007 DOWNTO 0);
         sta_send_frame_len0: OUT std_logic_vector (15 DOWNTO 0);
         rec_tcpipllc0      : OUT    std_logic_vector (2719 DOWNTO 0);
         sta_rec_ack0       : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT fisicoestacao080211
   PORT (
          clk_80211          : IN     std_logic;
          clk_10mhz          : in     std_logic;        
          rst_80211          : IN     std_logic; 
          sta_send_frame_len0: IN     std_logic_vector (15 DOWNTO 0);
          sta_send_frame0    : IN     std_logic_vector (3007 DOWNTO 0);
          tx_fromsta10       : IN     std_logic_vector (3199 DOWNTO 0);
          endtx00            : IN     std_logic;
          endtx000            : out     std_logic;
          endtx01            : OUT     std_logic;
          endtx0             : OUT     std_logic;
          channel_idle0      : out     std_logic;
          sta_rec_frame0     : OUT    std_logic_vector (3007 DOWNTO 0);
          sta_rec_frame_len0 : OUT    std_logic_vector (15 DOWNTO 0);
          sta_phy_tx0        : OUT    std_logic_vector (3199 DOWNTO 0)
       
   );
   END COMPONENT;
   



--##############################################################################
   -- Optional embedded configurations
   -- pragma synthesis_off
--   FOR ALL : SAR_Backoff USE ENTITY DNP3_802_11_lib.SAR_Backoff;
--   FOR ALL : SAR_MAC USE ENTITY DNP3_802_11_lib.SAR_MAC;
--   FOR ALL : SAR_PHY USE ENTITY DNP3_802_11_lib.SAR_PHY;
--   FOR ALL : SSM_MAC USE ENTITY DNP3_802_11_lib.SSM_MAC;
--   FOR ALL : SSM_PHY USE ENTITY DNP3_802_11_lib.SSM_PHY;
--##############################################################################
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   C_1 : estacao080211
      PORT MAP (
          clk_80211 => clk_80211,
          rst_80211 => rst_80211,
          clk_10mhz => clk_10mhz,       
         -- tcp_ip_llc interface
          sen_tcpipllc0 => sen_tcpipllc0,
          rec_tcpipllc0 => rec_tcpipllc0, 
          sta_send_ack0  => sta_send_ack0, 
          sta_rec_ack0   => sta_rec_ack0,
          
      --    -- phy layer interface
          endtx0              => endtx0,
          endtx000             => endtx000,
          channel_idle0       => channel_idle0,
          sta_rec_frame0      => sta_rec_frame0, 
          sta_rec_frame_len0  => sta_rec_frame_len0, 
          sta_send_frame0     => sta_send_frame0, 
          sta_send_frame_len0 => sta_send_frame_len0 
      );
   C_2 : fisicoestacao080211
      PORT MAP (
      
       
              
               
               
               
               
          clk_80211 => clk_80211,
          clk_10Mhz => clk_10Mhz,
          rst_80211 => rst_80211,
          
          -- time management interface
          sta_send_frame_len0    => sta_send_frame_len0, 
          sta_send_frame0        => sta_send_frame0,
          tx_fromsta10           => tx_fromsta10,
          endtx00                => endtx00,
          endtx000                => endtx000,
          endtx01                => endtx01,
          endtx0                 => endtx0,
          channel_idle0          => channel_idle0,
          sta_rec_frame0         => sta_rec_frame0,
          sta_rec_frame_len0     => sta_rec_frame_len0,
          sta_phy_tx0            => sta_phy_tx0
          
          
    );
   

END struct;
